### ISSUE TITLE
[feature request] Add UV data to Weather Meter

### ISSUE THREAD

**Issue by turbodude** [SilverAzide/Gadgets#101]
Something like this
![image](https://github.com/SilverAzide/Gadgets/assets/2452976/1200fcad-0019-411b-96bf-c13a39ce5a5e)

It's from [ModernGadgets](https://github.com/raiguard/ModernGadgets/), which stopped working recently. 

Also the temperature unit instructions from "HOW TO Change the default language or temperature units of the Weather Meter" don't seem to be working. Appending `&temp=c` to URLSite just breaks the gadget... I got to metric values by setting `Units=m` in that file

**Comment by SilverAzide** [comment]
Thanks for the feedback!  I've considered this also, but never implemented it since the original addgadgets.com gadget didn't support this either.  I'll look into adding this as an option, and most likely adopt the same style as ModernGadgets.

Thanks for the info about temp setting in the docs.  I guess weather.com changed their API so it no longer supports this option (it was an undocumented option).  I'll remove this sentence.

**Comment by SilverAzide** [comment]
One additional comment... I would strongly suggest not changing any variables in the `WeatherComJSONVariables.inc` file, including the units.  If/when you ever upgrade your Gadgets, this file is going to be replaced, and you will lose your settings.  The proper place to make manual changes is the `WeatherVariables.inc` file, as mentioned in the wiki.  You should not need to manually edit this file just to force the temps, you can just right click the skin and select `Custom skin actions` > `English (CA)` to force metric units.  If your locale is not one supported by weather.com, that would be the only time you'd need to manually alter the file (as described in the wiki).

**Comment by SilverAzide** [comment]
Completed.  This feature will be in the next release of the Gadgets.

![image](https://github.com/SilverAzide/Gadgets/assets/2706567/70b06197-eddb-4fd3-8004-ca99638b5b08)
