### ISSUE TITLE
Feature request - Display usage per physical core

### ISSUE THREAD

**Issue by candre23** [SilverAzide/Gadgets#106]
With the number of cores continually rising and hyperthreading being ubiquitous, there are just too many cores to display elegantly on modern systems.  But disabling per-logical-core display and just getting a single number isn't granular enough.  I would like to request a middle ground of per-physical-core utilization.

**Comment by miquelfire** [comment]
I don't think OSes even give you that option, which means the gadget may not have a way to tell what's an HT core, and what isn't, and even if it could, how would it know which belongs to which?

As an example, if this was possible, then my CPU gadget would display 8 cores instead of 16, but which cores are the ones result of HT? Is it the even number cores, the cores label 9 to 16? And in the case of 9 to 16, how do we know that core 9 is the HT core from core 1, and not core 8, or any other number in between?

**Comment by candre23** [comment]
I'm not familiar with exactly what the system does and doesn't expose.  I'm just setting up a system right now with two 14c/28t CPUs, and it's a *lot* of cores.  I was hoping there was something in between "all" and "nothing", but if it's not possible because there simply isn't a way to differentiate between physical and logical cores, then that's fair.

**Comment by SilverAzide** [comment]
@candre23 @miquelfire 
I understand where you are coming from!  The All CPU Meter _can_ tell the difference between HT and single-threaded cores.  However... Windows can't.  The CPU Meter gets its core usage info from the Windows Performance Counters database (same as HWiNFO), and the perf counters report usage per logical core (i.e., thread).  As a result, there's no way to show a subset of this data.

If this changes, you can be sure that I will definitely look at incorporating that capability into the CPU Meter.
