### ISSUE TITLE
Core clock is showing lower than actual core clock?

### ISSUE THREAD

**Issue by brandx96** [SilverAzide/Gadgets#112]
In HWinfo64 my core clocks are showing higher than what is displayed in the CPU Meter.

Also - is there a way to choose which core to display for the clock?

**Comment by SilverAzide** [comment]
Hello,

If you want the TL;DR version, jump to the last two paragraphs....  This is actually old news at this point and has been discussed in a number of issues.  See #27, #80, and #111.  There are lots of posts on the Rainmeter forums and elsewhere too.  Your question is sort of reversed, but everything is related.

You'll want to start here:  **[INFO: CPU performance exceeds 100%](https://github.com/SilverAzide/Gadgets/wiki/INFO-CPU-performance-exceeds-100#info-cpu-performance-exceeds-100)**.

The problem started with Window 8, when Microsoft changed the way they report processor performance.  No one really noticed until they made another even bigger change sometime around the Win11 22H2 release.  Basically, any application (including Rainmeter) that reported CPU performance based on the **time-based performance counters** started reporting performance numbers that appeared very low.  My Gadgets suite doesn't use these counters by default, they use the **utility-based counters** that are also used by Task Manager.

The "problem" with the utility-based counters is they can report performance that exceeds 100%.  This is by Microsoft's design, and MS does not consider it as a "problem"; they consider it the "correct" way to report performance on a modern CPU (per my article linked above).

So what can you do if you disagree with Microsoft and want to use time-based counters that _aren't_ messed up?  Well, you are out of luck.  However, after a lot of grumbling/flamewars from users on many forums, the MSI Afterburner devs came up with a fix. Martin (the HWiNFO dev) added this fix into HWiNFO v7.46 about a year and a half ago.  Now, HWiNFO's time-based counters look more like they were pre-22H2.

So, to answer your first question, HWiNFO is showing higher probably because you are looking at the HWiNFO "core usage" counters.  These are the tweaked counters that will not match anything in Windows, but according to some folks, are "more correct".  The counters Windows uses (and the Gadgets use) are the "core utility" counters, which also show in HWiNFO.  There is a CPU Meter setting "Use Legacy Mode" that you can enable to force using the old Windows 7 time-based counters, but these counters will read _very_ low if you are running Win11 22H2 or later, and thus they should be considered "broken".  I may someday enable use of HWiNFO's tweaked counters, but I have not done so yet.

For your second question: No.  The clock is showing the maximum clock of all cores, so if you have 15 cores running at 1 MHz and 1 core running at 5000 Mhz, it will show 5000.  However, if you want to trick the system, map all the HWiNFO core clock frequency variables (e.g., `HWiNFO_CPU0_Core0Clock`, etc.) to a single sensor entry, whichever core or cores you want.

**Comment by miquelfire** [comment]
I think you misunderstood the issue. If I read it correctly, it sounds like it's showing 1Mhz instead of 5000MHz using your example.

**Comment by SilverAzide** [comment]
No response. Closed.
