### ISSUE TITLE
SSID and signal not reported

### ISSUE THREAD

**Issue by kiefzzz** [SilverAzide/Gadgets#113]
So network meter including pro variant both pick up the traffic, internal and external IPs, successful ping, but SSID is not reported and neither is signal strength.

This is on Windows 11 24H2, wifi onboard is MediaTek Wi-FI 6E MT7922 (RZ616).

**Comment by SilverAzide** [comment]
I assume you also have a wired connection to your PC?  The Network Meter gadget reports your "active" network connection.  If your PC/laptop has both a wired and wireless connection, Rainmeter considers the active one the wired connection so this is what the gadget will show.  Unplug the network cable and you will see it will switch over to show your WiFi SSID and signal strength.

If you want to see the both the wired and wireless connection, you can use the Wireless Meter too.  This gadget looks at WiFi only.  Please note that some PCs will disable the WiFi adapter if a wired connection is available; just mentioning it since the Wireless Meter may also show nothing depending on your situation.

**Comment by kiefzzz** [comment]
Apologies, I wasn't clear, I am only using the Wireless Meter.  I have a wired NIC, but no connection there. No cable plugged in either. 

This gave me an idea and I disabled both bluetooth and wired nic card and refreshed but that unfortunately didn't help.

![image](https://github.com/user-attachments/assets/6e30c3d0-5e34-4a7c-bd78-76f7ce2ce472)

![image](https://github.com/user-attachments/assets/15eb6829-fb4c-4df8-b43a-0aea94098cfb)

![image](https://github.com/user-attachments/assets/edfe124d-983c-4dfd-9c78-4b54aaac5dbc)

![image](https://github.com/user-attachments/assets/2d8e0b09-971b-4b68-9f0b-3c1a3d0bef16)

**Comment by CBongo** [comment]
Also seeing this on Windows 11 24H2 with "Intel(R) Wi-Fi 7 BE200 320MHz" wireless adapter.  Still working fine in Windows 10 22H2, so I suspect Windows 11 or the 24H2 update broke it somehow.

**Comment by SilverAzide** [comment]
@kiefzzz @CBongo Interesting!  (Thanks a ton for the screenshots!)  My laptop has not upgraded itself to 24H2 yet.  The "Not Connected" message you are seeing (and missing signal strength) is because Rainmeter's WiFiStatus plugin is returning an error that says your wifi is not connected.  Obviously this is not true, so something must be glitched.  Since both of are reporting the same thing, please try the following.

1. Right-click the skin and select the `Edit skin` option.
2. Near the top of the file, you will see the following line:

   ![image](https://github.com/user-attachments/assets/da4e7554-8e08-4c17-8de2-cd50c91282a4)

3. The manual says if 0 doesn't work, try 1, 2, etc. until you find something that works.  So change the `WiFiInterfaceID` variable to 1, refresh the skin, and see if it works.  If it doesn't try 2, etc., until you run out of patience (lol).  I would think you would not have to try too many values since you probably don't have that many wireless NICs.

It is possible that somehow your Bluetooth adapter is being enumerated before your wifi adapter or something odd like that, maybe related to the 24H2 upgrade process.

Let me know if this works for you.  I don't have a way to test this myself at the moment.

**Comment by SilverAzide** [comment]
P.S.:  If this works, you'll need to make this change to all 4 network Gadgets skins.

**Comment by kiefzzz** [comment]
Disappointed to say that nothing helps here, I've changed it to 1-9 from 0 and it's the same.

**Comment by SilverAzide** [comment]
Dang it, I was afraid you might say that.  Hm... I'm running out of ideas then.  I have not seen any mentions of problems with the WiFiStatus measure on the Rainmeter forums.

Could you paste the skin code below into an .ini file in the Wireless Meter folder? Refresh Rainmeter, then right-click the Wireless Meter skin.  From the Variants submenu, select the ini file you created.  This file is purely Rainmeter measures with no tricky stuff.  If it works for you, then it would indicate a bug in the Wireless Meter logic someplace.

```ini
[Rainmeter]
AccurateText=1
BackgroundMode=2
DynamicWindowSize=1
SolidColor=0,0,0,255
MiddleMouseUpAction=[!Refresh]
Update=1000

;///////////////////////////////////////////////////////////////////////////////////////////////////
;                                              Styles
;///////////////////////////////////////////////////////////////////////////////////////////////////

[StyleTextInfo]
AntiAlias=1
FontColor=255,255,255
StringAlign=Left
X=0
Y=14r

;///////////////////////////////////////////////////////////////////////////////////////////////////
;                                             Measures
;///////////////////////////////////////////////////////////////////////////////////////////////////

[MeasureAdapterDescription]
Measure=SysInfo
SysInfoType=ADAPTER_DESCRIPTION
SysInfoData=Best
DynamicVariables=1

[MeasureAdapterState]
Measure=SysInfo
SysInfoType=ADAPTER_STATE
SysInfoData=Best
DynamicVariables=1

[MeasureInterfaceName]
Measure=SysInfo
SysInfoType=ADAPTER_ALIAS
SysInfoData=Best
DynamicVariables=1

[MeasureAdapterType]
Measure=SysInfo
SysInfoType=ADAPTER_TYPE
SysInfoData=Best
DynamicVariables=1

[MeasureNetworkIsWAN]
Measure=SysInfo
SysInfoType=INTERNET_CONNECTIVITY
SysInfoData=Best
RegExpSubstitute=1
Substitute="^-1$":"None","^1$":"Connected"

[MeasureWiFiSSID]
Measure=WiFiStatus
WiFiInfoType=SSID
WiFiIntfID=0
RegExpSubstitute=1
Substitute="^-1$":"None","^0$":"No Connection"

[MeasureWiFiQuality]
Measure=WiFiStatus
WiFiInfoType=Quality
WiFiIntfID=0

[MeasureWiFiList]
Measure=WiFiStatus
WiFiInfoType=List
WiFiListStyle=7

;///////////////////////////////////////////////////////////////////////////////////////////////////
;                                               Meters
;///////////////////////////////////////////////////////////////////////////////////////////////////

[MeterAdapterDescription]
Meter=String
MeasureName=MeasureAdapterDescription
MeterStyle=StyleTextInfo
Text="Active Adapter:  %1"
Y=0

[MeterAdapterState]
Meter=String
MeasureName=MeasureAdapterState
MeterStyle=StyleTextInfo
Text="State:  %1"

[MeterInterfaceName]
Meter=String
MeasureName=MeasureInterfaceName
MeasureName2=MeasureAdapterType
MeterStyle=StyleTextInfo
Text="Interface:  %1 (%2)"

[MeterNetworkIsWAN]
Meter=String
MeasureName=MeasureNetworkIsWAN
MeterStyle=StyleTextInfo
Text="Internet:  %1"

[MeterWiFiSSID]
Meter=String
MeasureName=MeasureWiFiSSID
MeterStyle=StyleTextInfo
Text="SSID:  %1"

[MeterWiFiQuality]
Meter=String
MeasureName=MeasureWiFiQuality
MeterStyle=StyleTextInfo
Text="Signal:  %1%"

[MeterWiFiList]
Meter=String
MeasureName=MeasureWiFiList
MeterStyle=StyleTextInfo
Text="Networks:#CRLF#%1"
Y=20r
```

**Comment by kiefzzz** [comment]
Seems like a pure rainmeter issue.

![image](https://github.com/user-attachments/assets/aa98b3e5-ba7a-4d5b-8c80-7dcb6e4fc49c)

**Comment by SilverAzide** [comment]
Well, that's interesting.  Not in a good way, but interesting.  I'll post this on the Rainmeter bug forum, perhaps the devs can offer up an idea about what could be going wrong.  Thanks for your help on this (@CBongo too), I really appreciate it.  I'll post back here if I discover anything.

**Comment by jsmorley** [comment]
I believe this addresses the issue:

https://forum.rainmeter.net/viewtopic.php?p=229084#p229084

**Comment by kiefzzz** [comment]
And that's it. Thanks @jsmorley for the solution, never would have thought of trying this, and thanks @SilverAzide for so diligently trying to help troubleshoot.

Besides the SSID and signal strength, can clearly see rainmeter is accessing location

![image](https://github.com/user-attachments/assets/1039850a-6d81-4ff3-95b6-641ec9e3335d)

**Comment by SilverAzide** [comment]
From the Rainmeter user manual:

## A Note for Windows 11 Starting with 24H2
Windows 11 has a new setting that must be toggled ON for WiFiStatus to be able to return any values.
It is Let desktop apps access your location in Settings / Privacy & security / Location.
_This setting will cause a Location icon to appear in the Notification Area of the taskbar._

**Comment by im-ukr77** [comment]
> I believe this addresses the issue:
> 
> https://forum.rainmeter.net/viewtopic.php?p=229084#p229084

thanks! that surprisingly worked.
