### ISSUE TITLE
Hiding Graphs

### ISSUE THREAD

**Issue by Frakasat** [SilverAzide/Gadgets#13]
Hi, I'm trying to disable graphs for Network, Drives, CPU and GPU meters. I commented lines below "Graph" sections but now I can't figure out how to resize gadgets to fit the new heights (removing blank sections at the bottom).
Can you please tell me where I need to modify files ?

Edit: typos

**Comment by SilverAzide** [comment]
The height of each skin is controlled by the `BgHeight` variable (found near the top of each skin file in the `[Variables]` section), with one exception.  For the best results, you can just alter the formula that is used by subtracting 42 or so pixels (or whatever the height of the graph is, I forget exactly).

For the All CPU Meter and Network Meter, just alter the formula, for example...
Change this:
`BgHeight=(206 - ([#*HideStats*] * 38))`
to this:
`BgHeight=(206 - ([#*HideStats*] * 38) - 42)`

(Be sure to make sure there are parentheses around this expression; in other words, don't just tack on "-42" to the end after the last parenthesis).  The Network Meter skins may require some additional work due to the fact that the graph is not at the bottom of the gadget, but hopefully it should not be too difficult.

For the GPU Meter, just change `BgHeight` to a formula:
`BgHeight=(222 - 42)`

The Drives Meter is different from the above, in that the height is a calculated value based on the number of drives currently active.  For this one, find the measure `[CalcBgHeight]` and change it like so:
```
[CalcBgHeight]
Measure=Calc
Formula=(30 + (CalcDiskCount * 50) + 8)
```
(i.e., removing the "- 42").

Removing the graph from any of the Gadget skins should be a similar process to these, with minor differences.  I tried to make it as uniform as I could.  If you run into any issues, let me know!

**Comment by Frakasat** [comment]
It's perfect i removed all graphs and blank spaces and replaced the drive one with horizontal bars. Thank you very much.
