### ISSUE TITLE
Replace HWiNFO

### ISSUE THREAD

**Issue by roncli** [SilverAzide/Gadgets#15]
Starting with version 7.00, HWiNFO64's free version is limiting shared memory time to 12 hours unless you pay for the Pro version.  Recommendation is to find something other than HWiNFO for the gadgets that use them.

I have downgraded to HWiNFO64 v6.42 (not easy to find, I found it at [https://www.filepuma.com/download/hwinfo64_6.42-27806/](https://www.filepuma.com/download/hwinfo64_6.42-27806/)) in the meantime.

**Comment by SilverAzide** [comment]
I will definitely be updating HWiNFO support.  The only skin that **requires** HWiNFO is the GPU Meter.  SpeedFan can supply CPU Meter with 100% of the data it needs, but SpeedFan won't do anything for the GPU Meter.

I've already post updated instructions for HWiNFO on all wiki help pages mentioning this 12-hour limit, and on the main DeviantArt page too.  Also, just to let everyone know, the official archive of all past versions of HWiNFO can be found at [https://www.fosshub.com/HWiNFO-old.html](https://www.fosshub.com/HWiNFO-old.html).

**See the following post on the Rainmeter forum:  https://forum.rainmeter.net/viewtopic.php?f=5&t=37106.**  There is some very good news in the following discussion.  Martin is going to create a beta with the ability for Rainmeter to use v7.0 without needing to pay (presumably because it will not use shared memory).  It will also not require a special plugin!  Hopefully it will be simpler to configure, but we shall see,

Hang in there everyone, a solution is coming!  Once it arrives, I will update all the Gadgets and release a new version.  The new version will require the Rainmeter 4.4 beta (sorry!).

**Comment by SilverAzide** [comment]
Update:
The HWiNFO author has released a beta that can be used by Rainmeter skins without needing to enable Shared Memory.  Implementation will be a little tricky, though.  More info [here](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160).

**Comment by quantuumsnot** [comment]
Nice shot in the leg tho
First, 7.00 gave a lot of problems - crashing systems (especially a pretty stable old high-end systems), killing stability of motherboards when using their fan control apps, etc

**Comment by SilverAzide** [comment]
So far I have not had any stability issues with the 7.01 beta.  🤞 !!

**Comment by SilverAzide** [comment]
All CPU Meter and GPU Meter have been rewritten to use the new HWiNFO "Sidebar Gadget" configuration.  This means no more HWiNFO plugin, no more Shared Memory Viewer, no more cutting and pasting a bajillion hex numbers.  The bad news is that your existing configuration will need to be redone, but hopefully it is a much simpler process.

This fix will be included in the next release of the Gadgets. The Gadgets release is planned for as soon as HWiNFO releases 7.02 for production use, so it should be soon (I hope).
