### ISSUE TITLE
CPU Gadet report >100% CPU usage when actual usage is nowhere max of a core

### ISSUE THREAD

**Issue by miquelfire** [SilverAzide/Gadgets#19]
I'm having an issue that is a bit odd. With my i7-10700, when the CPU is basically idle (Task Manager's details tab reports the idle process at 90%) and the clock is below about 4GHz, somehow CPU meter reports all cores at or above 100%.

I went to the [wiki page](https://github.com/SilverAzide/Gadgets/wiki/INFO-CPU-performance-exceeds-100) and switched to legacy mode, and now during normal use, I don't see any cores hitting 100%

I'm wondering if there's an issue with non-legacy mode reporting to cause this?

![sample image](https://raw.githubusercontent.com/wiki/SilverAzide/Gadgets/Images/All-CPU-Meter-Performance-Modes.png)
With this example image, the right side might have a max core value of let's say 40%-80%

**Comment by SilverAzide** [comment]
I am not seeing this behavior, but I don't have your exact CPU.  Could you post a screenshot of what you are seeing?  Try to get Resource Monitor and Task Manager in the same shot if you can.

See this example here.  Notice that the CPU Meter is showing (roughly) the same percent usage as Resource Monitor.  Task Manager does not show this same value, except when you look at the individual cores.  Notice how the peaks are getting clipped off in the graphs because they are going above 100% even though the overall percentage is not reflecting this.

![Image](https://user-images.githubusercontent.com/2706567/114404615-d874a700-9b73-11eb-8ad6-527884e2f771.png)

**Comment by miquelfire** [comment]
Ok, that is weird, it is what the wiki page describes, but I wonder why the usage jumps to above 100% on all cores when it gets close to the non-turbo speed? It seems the CPU wants to get off of Turbo Boost, but Windows reports all core above 100% as it gets near the non-turbo speed. Whatever causing this is making my CPU want to stay in the >4GHz clock speed range.
