### ISSUE TITLE
CPU Clock or Temp - Only 1 works

### ISSUE THREAD

**Issue by killer2239** [SilverAzide/Gadgets#24]
I just did an upgrade from i7-8086k to an AMD 5900x. I have everything working except if I tell it to report Index 0 for CPU Temp, then the clock speed stops reporting. If I remove 0 from the config file for the HWiNFO_CPU0_DTS_CoreMax=0  (0 is the index for the Tdie) then the clock speed starts reporting. Its like both can't run together. I even tried making it only report overall temp with that, and same issue.

**Comment by SilverAzide** [comment]
Did you reconfigure all your HWiNFO sensors for your new CPU?  I don't mean the indexes in the HWiNFO.inc file (although you have to do that as well), I mean the HWiNFO sensors on the "HWiNFO Gadget" tab in the Sensor Settings dialog.

The behavior you describe is essentially impossible without the sensor indexes being misconfigured, as the clocks have nothing to do with the temps.

[Check your sensor selections in HWiNFO](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-HWiNFO#how-to-configure-hwinfo), then [list the indexes and verify the assignments are correct](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-the-All-CPU-Meter-to-show-core-temperatures#using-hwinfo).  You can post your HWiNFOIndexList.txt file here if you need additional help.

**Comment by killer2239** [comment]
Yeah here is the HwiNFOIndexList.txt
`Index Sensor                                   Label                          Value
----- ---------------------------------------- ------------------------------ ---------------
0     CPU [#0]: AMD Ryzen 9 5900X: Enhanced    CPU (Tctl/Tdie)                51.4 °C
1     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Temperature                31.9 °C
2     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Core Voltage               0.738 V
3     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Fan1                       0 RPM
5     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Memory Clock               101.3 MHz
6     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Core Load                  1.0 %
7     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Memory Usage               3.0 %
8     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Fan1                       0 %
9     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Memory Allocated           744 MB
4     GPU [#0]: NVIDIA GeForce RTX 3090:       GPU Clock                      210.0 MHz`

And here is the HWiNFO.inc piece where I tell it to use index 0.
`; CPU #0 core 0 distance to TjMAX (degrees)
;   NOTE: for AMD CPUs ONLY, set the following value to blank, as AMD does not report TjMax values
HWiNFO_CPU0_DTS_DistToTjMax=
; CPU #0 maximum current core temperature (degrees)
;   NOTE: for Intel CPUs ONLY, this sensor reports the maximum temperature of all cores
;   NOTE: for AMD CPUs ONLY, set the following value to the index of the sensor corresponding to the
;         die temperature (Tdie) or CCD package (Tctl/Tdie)
HWiNFO_CPU0_DTS_CoreMax=0`

If I remove the 0 from the bottom and put a 0 on one of the HWiNFO_CPU0_DTS_Core0Temp= then the Clock piece under the Ryzen 9 5900X at the very top just reads 0. Its weird.

**Comment by SilverAzide** [comment]
Yes, I see the problem... as I thought, you have not configured HWiNFO or the skin properly.  You have not configured any of the clock sensor entries, the CPU fan,  nor the core temps per the guideline as described in the instructions.  _Please_ read all the instructions.

The instructions (either on the wiki page I linked above or in the HWiNFO.inc file itself) describe all the sensors you need to configure.  Add the missing sensors for the core clocks and CPU fan, then configure the temps per the instructions in the guides. 

What you are seeing is as expected; you are not seeing any clock speeds because you have not configured them.  When you disable the core max temp sensor, the skin is turning off all HWiNFO activity and showing only default values (as if HWiNFO is not being used at all). When you enable the sensor, it tries to display the clocks but sees nothing because you haven't configured the sensors.

**Comment by killer2239** [comment]
Ah! That was my mistake for sure. I didn't realize that enabling it made the other sensors need to be enabled and assigned like you just stated. Thank you so much for the quick tech support and helping me resolve the issue. Your skin is my absolute favorite!
