### ISSUE TITLE
Scaled down gadgets are transparent

### ISSUE THREAD

**Issue by gardenman** [SilverAzide/Gadgets#25]
The gadgets become transparent when scaled down to .88. Opacity set to 255.

This happens in version 7. This did not happen in version 5.5.

![gadgets](https://user-images.githubusercontent.com/42627735/131224369-21248b43-3d80-4fba-9df1-9d4997261b7a.jpg)

**Comment by SilverAzide** [comment]
Hello, sorry for the issues you are having.  Fortunately, I have some good news for you.  There actually isn't a bug, although you have run into a known issue.  The 5.5 and 7.0 versions do handle the background differently and the problem shows up...

It turns out that Rainmeter really doesn't like decimal numbers without leading zeros.  All you need to do, is change your scale factor to "0.88" and all will be well.  It has to do with the way Rainmeter parses formulas.  I should actually fix the Settings skin to ensure there is a leading zero on the input value, but it is a lot of work for something that rarely happens.

**Comment by gardenman** [comment]
Thank you, the 0.88 scale works. Keep up the great work on the gadgets.
