### ISSUE TITLE
Only detecting Drive C:

### ISSUE THREAD

**Issue by sdholden** [SilverAzide/Gadgets#47]
v7.3.0 only seems to be able to 'see' Drive C: and D:, but no mapped network drives which are assigned letters...am I missing something that changed?

**Comment by SilverAzide** [comment]
Hello!  No, I don't think anything has changed, as far as I can tell.

Mapped network drives have never been supported.  The reason is that Windows does not track performance stats for network drives, so the Drives Meter ignores them, as there is nothing to show other than the size (total/used/free).  It is possible to edit the skin to force them to be shown, but there's no way to show activity.

**Comment by sdholden** [comment]
Thanks!  I use rainforest on another laptop and it shows shared net drives, so thought I'd just confirm...

Regards,Stephen

⁣Get BlueMail for Android ​
