### ISSUE TITLE
Weather Meter in English and using the metric system

### ISSUE THREAD

**Issue by Pachuquero** [SilverAzide/Gadgets#5]
I have a minor issue showing Temperature and Visibility in the metric system (i.e. °C and km) **while also showing the phase of the moon in English**. It would seem the latter is not translated since it'll keep the language of whatever LocaleName I choose. 

For instance, in WeatherVariables.inc I change the following:

DisableLocale=1
LocaleName=de-DE
Lang=EN

and I get the following: 

![Rainmeter_2020-06-30_11-23-42](https://user-images.githubusercontent.com/5184994/86157277-62abbd00-bac4-11ea-97ad-5ebfeef98b3b.png)

The 5-day forecast will also retain week days in German as well as particular weather features such as thunderstorms, etc.

Perhaps these issues have everything to do with weather.com and not the gadget as such...

Otherwise, I just stumbled over the Rainmeter gadgets (and finally got rid of the antiquated original MS ones) and I truly appreciate all the efforts which have gone into these - and particularly I like the remakes done by SilverAzide, so many thanks and cheers!

**Comment by SilverAzide** [comment]
Hello!  Glad you like the Gadgets!

You are correct, this is partly due to weather.com.  The `LocaleName` is controlling the weather.com data, and `Lang` is controlling the labels in the Gadget supplied by me ("Humidity", etc.).

The phase of the moon text is actually coming from weather.com.  There is a trick you can use to get the units in metric and all the text in English.  The trick is to set the location to en-CA (Canada).  The easiest way to do this is to right-click, select "Custom skin actions", then "English (CA)".  If you want German labels, you can open the variables file and set `Lang=DE`, or leave it as `Lang=EN` or `Lang=NA`, but this will still have ALL weather.com data (including moon phase) in English.  If you want everything in German EXCEPT the moon, you'd need to make a small change to the skin and the translations file.  Let me know if you want to try this.

**Comment by Pachuquero** [comment]
Using Canada makes it all metric (and avoid weather.com translation errors) - I wrongly thought also Canada would be using miles for distance measures.  Cheers!
