### ISSUE TITLE
dedicated gpu not working

### ISSUE THREAD

**Issue by ouroborosc7** [SilverAzide/Gadgets#50]
compared to the previous one which i used the present version doesn't detect my gpu even when configured according to the index value shown in the notepad. and in addition to it some of the values are missing when compared to shared memory viewer
![20220914_150034](https://user-images.githubusercontent.com/105071875/190118417-e7479a01-ae50-4733-a43c-6fb5c59e7df1.jpg)
![20220914_150004](https://user-images.githubusercontent.com/105071875/190118441-5be3a62a-1b01-4685-8a7b-8e9549ec312c.jpg)
![20220914_150048](https://user-images.githubusercontent.com/105071875/190118469-6361a2e0-daca-41d7-951c-0e89134c7917.jpg)
![20220914_150613](https://user-images.githubusercontent.com/105071875/190119267-75f2bcdd-1275-4662-8af5-609ca6e2d7cb.jpg)

**Comment by SilverAzide** [comment]
Let me know what version of the Gadgets you are using and also what version of HWiNFO.  Also, you posted multiple screenshots of the Shared Memory Viewer; this application is no longer needed or used unless you are using an older version of the Gadgets.  The only application you need now is HWiNFO itself.

I can't tell much from the screenshots you sent, but it looks like your GPU Meter configuration is completely messed up.  Why are so many GPU 1 sensor indexes left blank?  This is your nVidia card, so you need to fill these out properly.  It looks like you have a second GPU Meter showing something.  What is this?  It looks like it's got CPU info instead of GPU info, or some mixture of both?  Please follow the **all** instructions listed at the top of the HWiNFO.inc file **exactly**.

If you still have trouble, please post your HWiNFO.inc file and HWiNFOIndexList.txt files here.

By the way, selecting all sensors in HWiNFO for gadget reporting is going to impact your system performance a noticeable amount.  I'd suggest removing unused sensors unless you use other skins that require them.  You do not need to select any disk drive or network card sensors, for example.  But this is up to you...

(Also, you do not need to take screenshots with a cellphone.  Just press Win-Shift-S to grab sections of the desktop or the active window.  PrintScreen (for the desktop) or Alt-PrintScreen (for the active window) work too.  This will place the picture on the clipboard, which you can save to a file.  If you are posting the HWiNFO index list report or the HWiNFO variables files, just attach them as text files instead of screenshots, as they will be complete and easier to read.)

**Comment by ouroborosc7** [comment]
[HWiNFOIndexList.txt](https://github.com/SilverAzide/Gadgets/files/9573072/HWiNFOIndexList.txt)
[hwinfo.txt](https://github.com/SilverAzide/Gadgets/files/9573092/hwinfo.txt)

the index list changes every time i open it. 
version of hwinfo that i use is 7.26-4800
![Screenshot 2022-09-15 132018](https://user-images.githubusercontent.com/105071875/190347917-b2588632-1e09-4806-a432-c2efc58e3f77.png)

as this does not support the uploading of hwinfo.inc file i have uploaded it as a .txt file

**Comment by SilverAzide** [comment]
Let me know if you are still having issues.

**Comment by ouroborosc7** [comment]
[HWiNFOIndexList.txt](https://github.com/SilverAzide/Gadgets/files/9605208/HWiNFOIndexList.txt)
[HWiNFO.txt](https://github.com/SilverAzide/Gadgets/files/9605209/HWiNFO.txt)
![Screenshot 2022-09-20 130707](https://user-images.githubusercontent.com/105071875/191196981-9d6e317c-2fcd-4745-b312-52f6d47feb1d.png)

gpu 1 still not working even after configuration

**Comment by ouroborosc7** [comment]
network meter pro doesn't show any bandwidth data but it shows in normal network meter

**Comment by SilverAzide** [comment]
OK, it looks like your GPU Meter (1) isn't showing anything because it is not active.  If you look at your sensor list (the one you attached), all the values are zero, which means it isn't active.  This is typical when using a laptop where the dedicated GPU (dGPU) is used only at certain times (like when gaming), and the integrated GPU (iGPU) is used the rest of the time to save battery.  Some laptops allow you to force the dGPU to be active all the time by changing a setting in the BIOS (nVidia calls it "Optimus" I think, and you'd want it turned OFF to force your dGPU to be active all the time.  This will kill your battery life, however.)  Anyway, it looks like your nVidia card is now configured properly from what I see, so as soon as it becomes active, the GPU Meter should "wake up" and start showing data.

As far as the Network Meter Pro is concerned, did you install the NetMonitor service?  This is required for the "Pro" gadgets.

**Comment by ouroborosc7** [comment]
now everything is working fine. as you said the gpu was in standby mode, but hwinfo doesn't report the values when in auto start mode so i have to  open it manuallyeach and every time. it would be better if the skin work on its 6.4 version of hwinfo by using instance value

**Comment by SilverAzide** [comment]
Glad you got it all working!  I'm not sure I follow you about the "auto start" mode.  HWiNFO 7.x has not changed the way it runs, as far as I know, it is the same a 6.x.  I agree it is a little bit difficult to get it to work without being annoying.  Check the [wiki article](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-HWiNFO), I posted screenshots of the best way to configure HWiNFO.  The only difference is you will want to check the "auto start" option.

The problem with 6.42 is that version is old and won't keep working forever.  Your only real choices are either pay for 7,x or use the free version of 7.x, and the free version requires a different way of configuring for Rainmeter.
