### ISSUE TITLE
Wireless meter displays the wrong internal IP

### ISSUE THREAD

**Issue by Ariche2** [SilverAzide/Gadgets#51]
When using both wireless and ethernet interfaces, both the Wireless Meter gadget and the Network Meter gadget display the same internal IP, which is false. It appears to be always displaying the internal IP for the ethernet NIC. See below, the difference between the gadget and my wireless interface's actual internal IP.
![image](https://user-images.githubusercontent.com/91376615/191750234-b690b5d1-027c-4ff2-a9fe-d73ed61905bc.png)
![image](https://user-images.githubusercontent.com/91376615/191750486-e7ecd119-2820-46cd-af96-5fb6fb50cf01.png)

**Comment by miquelfire** [comment]
Author will have to chime in on how to fix it, but it seems your wireless widget is pointing to your ethernet card instead of your wireless card/chip.

**Comment by SilverAzide** [comment]
> When using both wireless and ethernet interfaces, both the Wireless Meter gadget and the Network Meter gadget display the same internal IP, which is false. It appears to be always displaying the internal IP for the ethernet NIC. See below, the difference between the gadget and my wireless interface's actual internal IP.

What you are seeing (shown in the orange color) is the network adapter that Rainmeter has determined is the "active adapter".  Because of this, the IP address is also the one associated with your active adapter.  This is a little bit confusing, I agree with you.

A question like yours was just recently posted by someone else on the [Rainmeter forum](https://forum.rainmeter.net/viewtopic.php?t=20699&start=880#p209711). I will be making a change in the next release of the Gadgets to change this behavior.  I am planning on releasing it tomorrow or this weekend, so please check back.  If you can't wait, the forum thread describes how you can make the fixes yourself.

Thanks for your feedback!

**Comment by Ariche2** [comment]
Ahh, well that's fortuitous. I followed the small changes suggested on the forum (replacing `SysInfoData=Best` with `SysInfoData=#InterfaceWireless#` and `SysInfoData=#InterfaceEthernet#` respectively for each gadget) and it now works how I originally wished it to (i.e., one for each NIC).

**Comment by SilverAzide** [comment]
Excellent!  The update should be out in the next few days.  The Network Meter (Pro) won't be "locked" to the ethernet adapter since that skin is supposed to switch to show whatever is active, but now you know the trick to forcing it.  The Wireless Meter (Pro) will have the fix as you have it.  👍
