### ISSUE TITLE
Network Meter no longer shows Internal & External IP 

### ISSUE THREAD

**Issue by zme-ul** [SilverAzide/Gadgets#57]
a mobo upgrade and few W11 KBs later, the widget no longer shows the internal and external IPs

the used NIC, `Marvell AQtion 10Gbit Network Adapter` is the only NIC enabled in the BIOS, the WiFi and the other 2.5gbe Intel NICs are disabled

the issue manifested itself shortly after I upgraded the mobo to a ASUS Z690 Creator, but at almost the same time some Windows update(s) were installed (KB5018496, KB5018341)

I tried configuring the widget to auto and by selecting the Marvel NIC, it doesn't behave differently

**Comment by SilverAzide** [comment]
Well, it looks like the Network Meter is working... and it is telling you that you have a major problem.

If you are not seeing any internal IP address, that means Rainmeter attempted to identify your active adapter and retrieve the IP address associated with it, and failed.  I have seen this happen when you have a machine with multiple identically named network connections.  Normally, Windows will tack on a unique number if it sees identical names.  Here is my PC, for example (to see this, open the Network Meter Settings and click the link "List my network adapters..."):
```
Interface Name                            Connection                   Virtual State Type
--------------                            ----------                   ------- ----- ----
Intel(R) Ethernet Connection (17) I219-LM Ethernet                       False     2    6
Realtek USB GbE Family Controller         Ethernet 2                     False     2    6
Realtek USB GbE Family Controller #2      Ethernet 3                     False     2    6
Bluetooth Device (Personal Area Network)  Bluetooth Network Connection    True     2    6
Intel(R) Wi-Fi 6E AX211 160MHz            Wi-Fi                          False     2   71
```
Notice I have two Realtek adapters; Windows tacked on a "#2" onto the second one to ensure it is unique.  However, I've had some misbehaving software create duplicates, and I got a report from a user several months ago who somehow had *dozens* of adapters with identical names.  What happens then is Rainmeter sees an active connection, but fetches the IP address from another adapter with the same name that is dead or offline (because it really is offline or because it is a fake duplicate).

Make sure you are using the latest version of Rainmeter.  The Rainmeter devs added a fix to try to correct this issue (if it is the same issue you are having).  Another thing you can do is enable the Rainmeter debug log.  Restart Rainmeter, open the log and look through all the network adapters it has found on your machine.  Look for one that is marked as "Hardware=Yes" **and** "State=Connected" (both must be true).  It will look something like this:
```
DBUG (10:29:25.302) :  29: Name: Intel(R) Wi-Fi 6E AX211 160MHz
DBUG (10:29:25.303) :      Alias: Wi-Fi
DBUG (10:29:25.303) :      GUID: {945162DD-405E-4F4F-A0CC-ED10C95BECA9}
DBUG (10:29:25.304) :      Type=Wireless(71), Hardware=Yes, Filter=No
DBUG (10:29:25.304) :      IfIndex=12, State=Connected, Status=Up(1)
```
Once you find this, this should be your active ("Best") adapter.  Then, search for any additional adapters that have the exact same name or the exact same alias.  If you find any, this will confirm you have bad duplicates.

Next, your external IP address:
Your external IP address is obtained by making a call to a website.  By default, it uses an Amazon AWS service for this.  Open the Rainmeter About window and on the Skins tab, select the Network Meter.  Scroll to the bottom and see what the URL is for this, like so:
![image](https://user-images.githubusercontent.com/2706567/198671583-37d55428-ef04-4953-9e55-267a4852fc21.png)

If this is what you are seeing, then check the log for errors, as the website either isn't being called or is returning an error.  You can paste that URL into a browser and it should return a simple text string showing your address.

Again, your internal and external IP addresses are retrieved regardless of your settings or configuration, so if these are failing then it indicates a problem most likely unrelated to the Gadgets.

**Comment by zme-ul** [comment]
starting from the beginning

the Marvel NIC is the only one listed:
![image](https://user-images.githubusercontent.com/25272649/198691217-4c1f2297-2163-4754-8d9e-d85ae121faea.png)

RainMeter is the latest, 4.5.16 - Revision 3687

I looked trough the debug file, the active Marvel NIC is listed only once with its alias

and lastly:
![image](https://user-images.githubusercontent.com/25272649/198693041-3c169f4c-371c-4262-b580-2f4ac8dbf27b.png)
![image](https://user-images.githubusercontent.com/25272649/198693333-f5a732fd-5d1a-4092-b44a-77c4885e1818.png)

as you can see `MeasureIPLan` and `MeasureIPWeb` have the correct IPs

**Comment by SilverAzide** [comment]
So... Everything is working but you have nothing showing in the skin?  LOL, wow.  I guess I somewhat over-thought things thinking their was an actual problem.  Sorry about this.

I suspect you just toggled the display off, maybe by accident.  If you mouseover the skin, there is a small icon to the right off the "Int IP" line that looks like an eye, or an eye with a slash through it.  Click it, and you should see your data.

![image](https://user-images.githubusercontent.com/2706567/198696020-631d2770-d06d-4fec-9ffa-c891e62ab245.png)

**Comment by zme-ul** [comment]
> I suspect you just toggled the display off, maybe by accident. If you mouseover the skin, there is a small icon to the right of the "Int IP" line that looks like an eye, or an eye with a slash through it. Click it, and you should see your data.

oh dear lord .. I'm dumb 
I, or a colleague of mine, might've clicked randomly when I did the upgrade

**sorry to have wasted your time**

**Comment by SilverAzide** [comment]
My apologies as well!  I totally overlooked the obvious!
