### ISSUE TITLE
A few minor suggestions

### ISSUE THREAD

**Issue by sausje** [SilverAzide/Gadgets#58]
So I just found out that ModernGadgets stopped updating his version so I swapped to yours after his suggestion.

Now coming from there, I'm missing a few values that would be awesome to have back again.

CPU:
-Per core voltage.
-Top process inside this widget as a single line
-Option to disable fan graph line
-Why do RAM and pagefile have both text and bars?? Can't we disable one?

GPU:
-memory controller load bar+%
-video clock

Network:
-speedtest button for fast access to speedtest page
-ping??
-maybe add "censored" as text when hiding IP, so that you know it's on hide mode?
-the peak speeds would be nice to have up and down separated.

Disks:
-temperature per disk

These are some things I've noticed are absent (or I can't find them) from the widgets that I use compared to moderngadgets. Would be kind if you could add those.

**Comment by SilverAzide** [comment]
Hello!  Thanks for the suggestions.  Some of these can be done now and some are already planned for the next release.  So here is some feedback for you:

#### CPU Meter
+ Per core voltage - This can be done, but there is no space to show these values, unless you wanted to show them instead of temperatures.  There was much more usable space with the way ModernGadgets was laid out.
+ Top process - The next version will show from zero to 5 top processes.
+ Disable fan graph line - I will look into adding this.
+ RAM/Pagefile text/bars - I don't know why this is, but the original addgadget.com sidebar gadget did it this way, so I made the skin work the same.  I've had lots of feedback on this, and I am planning to change this in the next version so you can have either text, bars, or both.

#### GPU Meter
+ memory controller load bar+% - you can show the percentage now (and graph it if you want), but the bar isn't there.  That is much harder to do, and not sure I can do that in a generic way.
+ video clock - you can show this now (and graph it if you want).  No bar tho, same as above. 
![gpu](https://user-images.githubusercontent.com/2706567/198839791-0d24f9ca-caff-4715-936f-82846323fdae.png)

#### Drives Meter
+ Temperature per disk - this is actually extremely difficult to do properly.  The problem is that the Drives Meter shows _logical_ drives, but temps are per _physical_ drives.  The CPU Meter has a similar issue, but this case is worse.  Things like RAID arrays, storage pools, partitioned hard drives, etc., present huge problems since the drive letters and temps are not 1:1.  I've thought about this a lot over the years and I don't really see a way around this other than creating an entirely separate "physical drives" skin that relies on HWiNFO for everything (like the GPU Meter does).

**Comment by SilverAzide** [comment]
#### Network Meter
+ Speedtest button for fast access to speedtest page - I can look into adding this.  The old siderbar gadget had this too, but I never got around to adding it.
+ Ping - I can look into adding this too.
+ Maybe add "censored" as text when hiding IP, so that you know it's on hide mode - yeah, that could save some confusion, LOL.
+ the peak speeds would be nice to have up and down separated - I'd have to think about this one (i.e., how to lay it out).  The ModernGadgets way was optimal, but with this skin you'd end up with a huge blank space under the title which looks weird compared to all the other skins.

**Comment by sausje** [comment]
Awesome, thanks for the quick update on things.

So it's those additional sensors you mean for the GPU ones? HWiNFO_GPU0_Option1 and so on? Because I have no clue how to use those :(

Many things won't work the same because your gadget isn't virtually the same code I presume? (I'm not a coder, just a simple system manager) Otherwise you could've just imported his skin for the rm gadget, but I guess since the back-end isn't the same, that's a no go.

I'm looking forward to the update! Thanks again for the quick reply!

**Comment by SilverAzide** [comment]
Yes, the old MS Windows Sidebar platform was all javascript, so nothing can be salvaged from those.

For the additional sensors, yes, you have identified the right ones:
```ini
HWiNFO_GPU0_Option1=#HWiNFO_GPU0_CoreVoltage#
HWiNFO_GPU0_Option2=
HWiNFO_GPU0_Option3=
HWiNFO_GPU0_Option4=
HWiNFO_GPU0_Option5=
HWiNFO_GPU0_Option6=
; show/hide additional sensors on graph; 0=show, 1=hide
HWiNFO_GPU0_Option1_HideGraph=1
HWiNFO_GPU0_Option2_HideGraph=1
HWiNFO_GPU0_Option3_HideGraph=1
HWiNFO_GPU0_Option4_HideGraph=1
HWiNFO_GPU0_Option5_HideGraph=1
HWiNFO_GPU0_Option6_HideGraph=1
```
All you need to do to use these is:
+ Open the HWiNFO sensors and select the sensor entries you want to see (same config steps as you've already done).
+ Open the GPU Meter Settings and use the link to list the indexes.
+ Finally, for each index, add them sequentially (in whatever order you want) to the options, like so:
```ini
HWiNFO_GPU0_Option1=26
HWiNFO_GPU0_Option2=13
HWiNFO_GPU0_Option3=42
HWiNFO_GPU0_Option4=31 ...etc.
```
+ If you want to see these sensors graphed, then change the corresponding "xxx_Hide_Graph" option to "0".  You won't want to do this for sensors that return yes/no or something, just one that return percentages and other numeric values.

That's it!

**Comment by SilverAzide** [comment]
Enhancements included in next release.

Exceptions:
Not possible to do core voltages due to lack of available space for displaying values.
Not possible to do disk temps with this skin.
