### ISSUE TITLE
Group the All CPU Meter by P-Cores and E-Cores

### ISSUE THREAD

**Issue by DocBrown101** [SilverAzide/Gadgets#59]
Are there any plans yet to group the All CPU Meter by P-Cores and E-Cores or highlight it in some other way?

**Comment by miquelfire** [comment]
I assume if Silver doesn't even have access to a 12-gen or higher Intel system, he can't even know begin to know where to look for this info.

Also, it wouldn't surprise me if Windows 11 was required to even see P-Cores and E-Cores as their own thing anyway. At best, Windows 10 might just see them different NUMA groups, but nothing more than that. Wow, now I want to know how those processors appear on Windows 10.

**Comment by SilverAzide** [comment]
Hello!
I have a i9-12950HX with 8P+8E cores.  You can't really tell which cores are which unless you assume P cores are the ones with 2 threads/physical core, and that's not guaranteed since you can disable hyperthreading.  HWiNFO tells you in their labelling which are which, but I don't know of a way to figure this out using just Windows itself.  Windows seems to know deep down which cores are which, but task manager (for example, or resource monitor) doesn't look any different.

Assuming there was a way this could be figured out, do you have an idea of how you would highlight this info, especially given that the gadget is so cramped for space?  I could stick a tiny "P" or "E" someplace on the bar maybe...

**Comment by SilverAzide** [comment]
P.S.: The cores **are** grouped, by they way, but it's not something I did.  Luckily, the P cores are first in the order, followed by the E cores.  Not sure if this is always going to be the case, but on the machines I've seen so far, that's how they come up.

**Comment by DocBrown101** [comment]
Since HWiNFO has the information, why not map it over there? For the core temperatures you also need HWiNFO.
![image](https://user-images.githubusercontent.com/11892773/201532219-90f9a3b8-5396-4d5e-b67f-4f08e8846c9d.png)

**Comment by SilverAzide** [comment]
Yes, understood... but I think you might have missed my point.  There isn't any sensor data that HWiNFO (or Windows for that matter) exposes that says "this is a P core" or "this is an E core".  Only the HWiNFO sensor **labelling** says this, and that can be changed/renamed by the user, and probably changes based on the language settings.

But even if all these things were known, the question still remains where or how to display this information.  The skin is completely filled (no empty space left) so however it is done would need to be via a color or background shade, etc.

**Comment by DocBrown101** [comment]
I would visually change the CPU bar. It would probably be enough to display only the efficient cores in a paler color.

**Comment by SilverAzide** [comment]
Seems like a reasonable way to do it... if it is ever doable.
