### ISSUE TITLE
All CPU Meter Not Displaying Bars / RAM

### ISSUE THREAD

**Issue by viTRifY13** [SilverAzide/Gadgets#66]
Hi,

I have no idea what happened, but the bars / ram / graph are no longer showing on the CPU Meter.  I originally had a 7900X CPU and it worked fine, but then I upgraded to a 10980XE and this meter no longer seems to work.  I've completely uninstalled HWInfo64 / Rainmeter / Gadgets including all installation folders, and reinstalled, but I can't seem to get this working again.  

My HWINFO seems to be working, that gadget is writing to the registry continuously, but All CPU Meter doesn't seem to be pulling from it.  I've checked the configuration 100x and I'm a bit lost on what to troubleshoot next.

Any help / suggestions on where to look?  I tried looking through the *.inc files to see if a line of code with 36 processors was breaking the script, but didn't see anything obvious.  Wasn't exactly sure how the All CPU meter was obtaining RAM / Page file info, but given that's showing 0, where does the script pull that info from? 

Thanks in advance!  This is a fantastic gadget that I would really like to get working again

![image](https://user-images.githubusercontent.com/4000974/209834445-a7b6831e-232b-4a9c-bc53-9f155a77bac9.png)

**Comment by SilverAzide** [comment]
Sorry you are having problems!  From the appearance of your screenshot, it looks like the issue is not HWiNFO or the All CPU Meter.  As a first guess, it actually looks like your Windows performance counters database is corrupted.

Try the instructions on the Gadgets wiki page here:
[HOW TO: Fix your Performance Counters database](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Fix-your-Performance-Counters-database)

P.S.: As an unrelated side issue, I could not tell if you are running Windows 11 or not, but if so, you are going to want to UNcheck the "Use Legacy Mode" checkbox, especially due to MS's recent changes; otherwise, your CPU/core usage will be reported very low and will not match Task Manager or HWiNFO.

**Comment by viTRifY13** [comment]
That worked!!!!  Thanks so much!  I spent an embarrassing amount of time trying to troubleshoot that

**Comment by SilverAzide** [comment]
Good news!  Glad it worked! 👍
