### ISSUE TITLE
Drivers Meter Temperatures 

### ISSUE THREAD

**Issue by Alex-Mirov** [SilverAzide/Gadgets#68]
Hello

Is it possible to show drivers temperatures on this gadget? 

Thanks

**Comment by SilverAzide** [comment]
Hello!  There has been a lot of interest in doing this, but unfortunately I really don't see a way to achieve this reliably.

The problem is that the Drives Meter shows **logical** drives.  This means that drives on partitioned hard disks, RAID arrays or Storage Spaces, etc., do not match up with their physical drive counterparts.  For example, how can I report the temperature of a logical drive that is actually a RAID 5 array, or a Storage Spaces array?  The number of combinations of logical and physical drives is huge.  In addition, HWiNFO reports temps on a physical drive basis and it is extremely complicated to figure which logical drive is associated with the physical drive (if any).

So while in theory it is easy to show drive temperatures in the simplest situations where there is a one-to-one mapping, it is rather difficult to do in a manner that works in all situations.

One alternative I have considered is creating a variant Drives Meter that shows physical drives instead of logical drives.  So far I haven't had the time to attempt such a thing, or see if it is of any value to anyone.

**Comment by MononeV** [comment]
@SilverAzide What about let the users fill in the HWINFO sensor # correspondingly instead of auto match, since we've already done that with CPU & GPU meters?

**Comment by SilverAzide** [comment]
> @SilverAzide What about let the users fill in the HWINFO sensor # correspondingly instead of auto match, since we've already done that with CPU & GPU meters?

Hello!  I'm not exactly sure I follow you.  Are you suggesting that the skin let the user map the sensors for the physical drive to the logical drive?

If so, this is pretty much how you'd have to do it anyway, but most importantly it won't solve any of a bunch of problems.  It won't solve issues with partitioned drives or drive arrays, where physical drives do not map neatly to logical drives.  And it won't solve issues where physical drives change their order from one boot to the next.  Depending on your system, you could have 3 drives (C:/D:/E: for example) boot up in 0/1/2 order one time and other time it would be 1/0/2 order.  Happens all the time with mechanical drives, which would throw off any mapping you would do.

So, as I mentioned above, the only way this will work is with a variant Drives Meter skin that uses physical drives and ignores logical drives completely.  It would be totally dependent on HWiNFO, I would think, since using PerfMon data is difficult for physical drives due to how you have to fetch the data.

**Comment by MononeV** [comment]
> It won't solve issues with partitioned drives or drive arrays, where physical drives do not map neatly to logical drives.

I don't see a problem here cause I can choose which to map the sensor and which sensor to map. I can map the physical drive to just one partition, or I can just map the hottest physical drive in an array. It would up to the user.
> And it won't solve issues where physical drives change their order from one boot to the next. Depending on your system, you could have 3 drives (C:/D:/E: for example) boot up in 0/1/2 order one time and other time it would be 1/0/2 order. Happens all the time with mechanical drives, which would throw off any mapping you would do.

Well, I notice the random drives order in Linux but not much in Windows, not without a hardware change. I think it would be a risk we have to take. Need to mention that the sensor # for CPU & GPU meters also change upon a hardware change. So we have to remap the sensors after hardware changes anyway.

Anyway, I'm just saying that it would be nice to have drive temp display integrated into the drive meter. I understand your concerns, but having the option for drive temp is always better than nothing.
