### ISSUE TITLE
Show top Network processes??

### ISSUE THREAD

**Issue by EdLorenzQAT** [SilverAzide/Gadgets#69]
Asking to see if any of the network gadgets also show the top network processes.
Processes that are consuming network resources?

Thanks and keep up the good work,
Ed

**Comment by SilverAzide** [comment]
Hello!  Glad you are enjoying the Gadgets!

Well, I would love to be able to do this too!  In fact, this was the second gadget I wanted to create -- until I discovered this is practically impossible.  ...For me, anyway, LOL.

It turns out that this is incredibly complex.  There is no API in Windows (that I can comprehend), or performance counter, or single/simple WMI query, that will obtain this information directly that I am aware of.  I have no clue how Windows Resource Monitor is able to do what it does on the Network tab, for example.  There are a few third-party tools that do this, like NirSoft's NetworkTrafficView for example, but there's no way to hook this into Rainmeter.  There is a free 3rd-party library available (https://npcap.com/) that can be used, but building a Rainmeter plugin that uses this is far beyond my capabilities.

If I learn anything else about this topic, you can be sure a Gadget that does this will be at the top of my to do list!

**Comment by EdLorenzQAT** [comment]
Understand, thanks :)
