### ISSUE TITLE
Weather Meter Stalled at "Connecting"

### ISSUE THREAD

**Issue by kennylee33** [SilverAzide/Gadgets#72]
Hi Silver,

I had to reset my PC and reinstall Rainmeter and your Gadgets.  Everything is working well except the Weather Meter, which is blank except for the "Connecting" message at the bottom of the window.  Any thoughts?

**Comment by kennylee33** [comment]
I see this is fixed in 7.5.  There's no need for you to reply.  Thanks for Gadgets!

**Comment by Henry-Jones** [comment]
Hello,

I currently have the very same problem in 7.6 (just updated because 7.5 showed the same behavior).

It also happens on two different systems, so apart from a recent windows update they do not have much in common.

Is there something to check ?

**Comment by SilverAzide** [comment]
Sorry to hear you are having issues.  To figure out what is going on is going to require some detective work on your end.

First, is the Weather Meter showing weather for any location?  In other words, when you install it, it will default to New York City.  Is that working?

- If not, the problem is most likely between you and weather.com.  Open the Rainmeter About window.  Look for errors in the Rainmeter log on the Log tab.  Also, go to the Skins tab and select the Weather Meter.  Look for the meter `@EntireSiteSuperParent` and right-click it and select "String: Copy to clipboard".  Paste the text into Notepad to read it.  Normally, this is a large block of data in JSON format.  If the data is blank, then you are not even reaching the weather.com site.  Otherwise, you might see a message in this text, which will indicate the problem.  Post that here if you need help.
- If so, then it might be your location data is invalid.  Make sure you enter the correct latitude and longitude coordinates for your location.  Use the Search option to find lat/longs.

Let me know what you find.

**Comment by Henry-Jones** [comment]
Hello,

obviously I wrote too fast, after two days the gadgets worked again. But If it ever happens again, I now know what to do and where to look. At them moment, the expected block of JSON is there and the gadget displays the content accordingly.

Thanks for the quick response.
