### ISSUE TITLE
Request for Drives meter to map network drives

### ISSUE THREAD

**Issue by liam-maps** [SilverAzide/Gadgets#74]
Hi!
I really like and appreciate the effort of maintaining this set of gadgets, and it'll be cool to map network drives too.
I have a NAS with several mappings and I like to watch disk usage at glance.
Thank you for your work.

**Comment by SilverAzide** [comment]
Hello!  I'd like this too, but unfortunately it is not possible.  The problem is that network drives are not really drives, and Windows performance counters do not show them as logical drives (you can't see them in either Performance Monitor or Resource Monitor).  As a result, I've disabled the skins from being able to see these, since there isn't a way to show any performance/usage stats.

However, if all you want to see is _disk space_, then you CAN alter the skins so they will work.  You will not see any read/write data or graph activity, just disk space (used/free/total).

Let me know if you want to try this; it will require editing the skin files.  It will require you to map a drive letter as well, unless you want to make even more skin changes.

**Comment by SilverAzide** [comment]
See the instructions here for more:   https://github.com/SilverAzide/Gadgets/issues/38#issuecomment-1055727289.
You will need to uncheck the **Show Disk Percent Time Histogram** option.
