### ISSUE TITLE
Feature Request: Packet Loss Monitoring

### ISSUE THREAD

**Issue by derekakelly** [SilverAzide/Gadgets#79]
First off, big fan of your work, thank you!

Could you add an option for packet loss monitoring next to the ping speed section of the networking gadgets? It matters most to me with Wi-Fi, but it would also be useful when wired. Perhaps a percentage of the last 5 minutes or so?

Thanks,
-DK

**Comment by SilverAzide** [comment]
Hello!  Thanks, and glad you are enjoying the Gadgets!

Regarding the packet loss stats, that could be nice... but where can I get that info?  If it's not something I can get from PerfMon (performance counters database), then it's pretty unlikely since there's nothing built into Rainmeter that would tell this, as far as I know.  (The Ping plugin doesn't tell you anything except the ping time.)

I see some articles online about checking perfmon for "segments retransmitted", but it's not really clear to me what that gives you.  The only other thing I can think of is to constantly ping an address and graph the return times; if they start escalating, then you know there's a problem.  There is a Ping Monitor gadget in the [Gadget Additions suite] (https://github.com/Dudebaker/Gadgets-Additions) that does this.  Would that work for you?

**Comment by SilverAzide** [comment]
No response
