### ISSUE TITLE
CPU Meter - CPU Usage reaching 116% instead of 100% on benchmark

### ISSUE THREAD

**Issue by ValP90** [SilverAzide/Gadgets#80]
Hello !

The usage percentage reported per cores in the CPU Meter gadget seems a bit off.

It can go higher than 100% (116% in my case).

The "Core utility" seems to be the only sensors able to report values higher than 100%. Do you think it is possible to change that to report "Core usage" instead ?

Thanks a lot for your work !

**Comment by SilverAzide** [comment]
Hello!  Glad you like the Gadgets!

This behavior is by design, and is how Windows has reported performance since around the Windows 8 days.  It was not super-obvious until recent changes to Windows 11.   See the wiki article here:  [CPU performance exceeds 100%](https://github.com/SilverAzide/Gadgets/wiki/INFO-CPU-performance-exceeds-100#info-cpu-performance-exceeds-100).
Also see duplicate issues #27 and #78.

If you want the performance to show like it did in Windows 7, then you can check the **Use Legacy Mode** option in the Settings skin.  You should be warned however, that since Windows 11 H22 (or so), Microsoft has made a change that severely underreports CPU usage, especially for newer hybrid CPUs.  This mode will not match what is shown in Task Manager, which uses the newer core utility measures.

If you are looking at HWiNFO, that app has altered the way "core usage" is reported to better match how Windows reported performance since before Win 11 H22.  Unfortunately, the CPU Meter does not use HWiNFO for this at this time, it uses Windows performance counters.
