### ISSUE TITLE
gpu meter doesnt work still

### ISSUE THREAD

**Issue by huggywuggybest03** [SilverAzide/Gadgets#87]
sorry i didnt reply i forgot but I can't run HWiNFO and it says this:
![image](https://github.com/SilverAzide/Gadgets/assets/135007348/65d37066-88b2-45ac-a157-7b202b46dcb2)
I already configured it but it just wont run.

**Any ideas?**

Also what line is the configuration on cuz im using notepad

**Comment by SilverAzide** [comment]
Are you serious?  You've already posted screenshots here https://github.com/SilverAzide/Gadgets/issues/85#issuecomment-1795507963 showing you've configured HWiNFO and have it running.  The message you posted above means exactly what it says, so I'm not sure why you need me to explain it.  HWiNFO must be running in order to interface with it and it clearly is not running, so therefore the message is being displayed.

When you say "I can't run HWiNFO" what exactly do you mean?  Is HWiNFO giving you some sort of error?  You ran it before, so why can you run it now?

**Comment by huggywuggybest03** [comment]
I know, but i didnt update it

**Comment by huggywuggybest03** [comment]
I still got 7.6.4 and I gotta reboot my pc for the update screen to appear

**Comment by huggywuggybest03** [comment]
By I can't run it, basicially I try opening it up, nothing happens. No errors or anything

**Comment by huggywuggybest03** [comment]
gtg bed ill reply in the morning

**Comment by huggywuggybest03** [comment]
alr im back and im still confused on why it isnt working

**Comment by SilverAzide** [comment]
How *what* isn't working?  As far as I can tell, you have not answered any of my questions nor done anything I asked you to do.  You need to be extremely clear; I can't see what you have done, so you need to describe the problem it step by step.

**Comment by huggywuggybest03** [comment]
alright.
step 1: I downloaded a GPU meter and it didn't work
step 2: I tried to change the index but that didn't work either
step 3 (what I'm going to try to do as u said): go to the line for GPU and fill in from the index

**Comment by SilverAzide** [comment]
You need to enter the **sensor index numbers** into the HWiNFO.inc file, not the values that the sensor is reporting.  None of the items entered in your screenshot are correct.

**Comment by huggywuggybest03** [comment]
oh

**Comment by huggywuggybest03** [comment]
I fixed it, thanks for the help!
