### ISSUE TITLE
CPU Temps stopped working

### ISSUE THREAD

**Issue by CallMeCJUnderscore** [SilverAzide/Gadgets#89]
I just updated HWiNFO to the latest version, and downloaded the latest version of Gadgets. That means I am on Gadgets v 7.6.0 and HWiNFO64 Pro 7.68-5300. As of this update, the CPU Temperature has stopped reporting in the widget, even though it both shows up in HWiNFO's Sensors page, and in the Indexes list. Everything else works perfectly. The ordering has not changed, nor have the numbers, and yes it does not display on the widget. I would use SpeedFan, as that displays my CPU Temps on the widget, but it doesn't report my fan speeds, which I like to keep track of.

## With HWiNFO running
![image](https://github.com/SilverAzide/Gadgets/assets/36345590/53ce655a-1a51-4e0f-8188-77c8a6599d55)
![image](https://github.com/SilverAzide/Gadgets/assets/36345590/0743f1ee-8099-4d26-af87-b458dfe5b066)
The only reason the fan percentage is so high is because my computer has mainly been idle since I did the updating, but that doesn't explain the lack of temperature reading.
![image](https://github.com/SilverAzide/Gadgets/assets/36345590/3ed6ddad-e013-4d64-8fc6-ce5ea77adfff)

## With SpeedFan running instead after clearing the relevant indexes
![image](https://github.com/SilverAzide/Gadgets/assets/36345590/b97d7f32-839f-4f73-92e6-3d290ca1b9d9)

For some reason, toggling "Show Temperatures Per-Core" makes none of the temps appear, regardless of program being used for monitoring.
![image](https://github.com/SilverAzide/Gadgets/assets/36345590/2ef1f3c2-4210-41fe-aa88-9900210d7940)

Any help with this would be greatly appreciated!

**Comment by SilverAzide** [comment]
I configured my CPU Meter to display like yours and it appears to be working fine for me:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/c73b4927-8d16-4362-9beb-61ff0291dc08)

Make sure the setting "Show Temperatures Per-Core" is UNchecked, like so:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/679636a5-d329-40c3-91f2-46c69e20ae27)

Do these settings work for you?

---
>For some reason, toggling "Show Temperatures Per-Core" makes none of the temps appear, regardless of program being used for monitoring.

This is correct.  You have unchecked the "Show Usage Per Logical Core" option, so the skin cannot show per-core temps (because there is no place to show the values); therefore if you enable this option, it can't show anything.  The only correct setting in this case is to also disable the per-core temps.  I could force the per-core temps option off if you turn off per-core usage..., maybe I will add that into the next version, but I didn't want to force these settings to be linked because for AMD users the settings may need to be independent.

**Comment by SilverAzide** [comment]
**UPDATE:  I found the problem!**

Looks like the problem is HWiNFO!  I was running 7.66, so I upgraded to the HWiNFO version you are using and I now get the same behavior as you reported.

It appears that for some oddball reason, they changed the Core Max temperature sensor.  This sensor is critical for displaying the temperature bar when the per-core temps are disabled.  Very annoying.

To fix this problem, you have to open the HWiNFO Sensor Settings and, on the "HWiNFO Gadget" table, re-select the Core Max temperature sensor.  If you are like me, you'll see the sensor got unchecked.  Rechecking it will instantly fix the error.  On my machine, the index ended up back at the same number, but I suppose it could shift for some people.

Let me know if this fixes the issue.

**Comment by CallMeCJUnderscore** [comment]
I had to completely retool what was getting reported the gadget page, and so the indexes were all over the place and completely different, but we're good now. I reset the fan numbers just in case some stuff got fucky, but otherwise, we look completely set. Thank you for the help.

![image](https://github.com/SilverAzide/Gadgets/assets/36345590/2718b6da-406f-4483-8e46-ea4c5945cbdf)
