### ISSUE TITLE
[Enhancement] support for additional options for CPU Meter like in GPU Meter  

### ISSUE THREAD

**Issue by Mint-Martini** [SilverAzide/Gadgets#92]
Hello just wanted to say thanks for all the cool stuff, I love having monitoring widgets! 

As for the enhancement, In the GPU Meter section they have the ability for monitoring additional things 

![image](https://github.com/SilverAzide/Gadgets/assets/26099314/9f03777f-b886-42bc-8b20-70953feca4ef)

I use this currently to monitor additional hardware  such as All in one CPU Cooler (Called Liquid Temperature) .  Under the current configuration, it is listed under the GPU meter. However it would make more sense under the CPU Meter Section  

![image](https://github.com/SilverAzide/Gadgets/assets/26099314/01cde57b-4b6a-4744-b42a-3289859e3cef)

Not a big deal but would def be appreciated!

**Comment by SilverAzide** [comment]
Glad you are enjoying the Gadgets!  Yes, this would be a good enhancement, but I don't think I'll be adding this sort of thing to the CPU Meter (at this time).  The reason is mainly because the CPU Meter is so insanely complicated already, adding anything else to it is kind of a nightmare.  Especially with folks who want to show per-core usage, the skin it getting to the point where it nearly fills the screen from top to bottom.

This is partly why I added the dedicated HWiNFO Meter skin.  You could add your AIO cooler to it, plus whatever other goodies you like.  Note that you can change the title of the skin (plus create multiple skins), so it can say whatever you want, like if you want to create a dedicated disk temps skin, plus whatever other HWiNFO-based skins you can think up.

Would this be a decent work-around for you?

**Comment by Mint-Martini** [comment]
Absolutely!! Thanks I didn't even notice the HWiNFO skin! That's a good workaround ! Thank you so much for the reply!
