### ISSUE TITLE
Not opening the windows under "HWiNFO Config" in CPU Meter and GPU Meter

### ISSUE THREAD

**Issue by rockychf** [SilverAzide/Gadgets#93]
![HWiNFO not show up](https://github.com/SilverAzide/Gadgets/assets/138271240/2368e6ee-72d9-4547-89b9-52e3f62c1f51)
I tried to reinstall the Gadgets v7.6, but those buttons under HWiNFO Config did not prompt out anything in the settings of CPU Meter and GPU Meter, may I know how to fix it? Thank you.

**Comment by miquelfire** [comment]
Do you have HWiNFO installed and running?

**Comment by rockychf** [comment]
![image](https://github.com/SilverAzide/Gadgets/assets/138271240/0e6cdb7e-f435-4e8f-a0a6-4b6f431bf7b8)
Yes.

**Comment by SilverAzide** [comment]
First, my apologies for responding so late to your question.  This is actually caused by a misconfiguration of Rainmeter.  Fortunately, this is a simple fix.

Right-click the Rainmeter icon in the notification tray and select **Manage**.  Select the **Settings** tab.  Your **Editor** option is most likely the problem here; possibly it is set to an invalid executable.  Use the "..." button to select a valid executable; you can use Windows Notepad if you don't have a preference.

Once you correct this setting, you'll need to restart Rainmeter.  At that point, the Settings link will work properly.
