### ISSUE TITLE
Network Meter freezes

### ISSUE THREAD

**Issue by mbartlett21** [SilverAzide/Gadgets#94]
This morning I had my network meter freeze on me.

The settings under NetworkVariables.inc were:
```
InterfaceBroadband=Bluetooth Device (Personal Area Network)
InterfaceEthernet=Realtek USB GbE Family Controller
InterfaceWireless=Intel(R) Wi-Fi 6 AX200 160MHz
```

Clearing the InterfaceWireless fixed it, and upon further investigation, Windows says it is in the middle of connecting to WiFi, even though it is actually plugged in to ethernet:
![image](https://github.com/SilverAzide/Gadgets/assets/29034492/921d0720-a5db-4ab8-afbc-04c33b53d3ac)

**Comment by SilverAzide** [comment]
Hm.  Not really sure what to tell you on this.  I'm not sure this is a problem with the Network Meter, sounds more like a Windows issue based on your investigation of the problem.  The skin only displays what Rainmeter reports, so if it is stuck, then that would indicate that Rainmeter itself can't figure out what network adapter is active (just like Windows itself shows).  In fact, one could argue the skin is working perfectly... altering you to a problem.

Removing the adapter from the configuration would mean the adapter is just being ignored, but nothing is really "fixed".  Perhaps a reboot, or toggling airplane mode, will give Windows the kick it needs to figure out what adapter is active.

I will close this issue since there is nothing I can do about this, but feel free to reopen it if you can gather any additional information.

**Comment by mbartlett21** [comment]
@SilverAzide 
Agreed. I figured on opening the issue anyway for a workaround in case other people get the same problem.

Upon restarting Windows seems to have figured itself out.

> The skin only displays what Rainmeter reports

Ok. I didn't know if it was using a custom plugin or not.
